services:
  n8n:
    image: n8nio/n8n
    container_name: n8n_automata
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - TZ=America/Sao_Paulo
      - GENERIC_TIMEZONE=America/Sao_Paulo
  chromadb:
    image: chromadb/chroma
    container_name: chroma_automata
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/.chroma/
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_automata
    restart: unless-stopped
    ports:
      - "8501:8501"
    env_file:
      - .env
    command: streamlit run src/dashboard.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - chromadb

  transcription-service:
    build:
      context: ../services/transcription
    ports:
      - "5001:5001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:5001/docs')\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  text-analysis-service:
    build:
      context: ../services/text_analysis
    ports:
      - "5002:5002"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:5002/docs')\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  embedding-service:
    build:
      context: ../services/embedding
    ports:
      - "5003:5003"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:5003/docs')\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  carousel-service:
    build:
      context: ../services/carousel
    ports:
      - "5004:5004"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:5004/docs')\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  video-cut-service:
    build:
      context: ../services/video_cut
    ports:
      - "5015:5005"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:5005/docs')\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  multimodal-service:
    build:
      context: ../services/multimodal
    ports:
      - "5016:5006"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:5006/docs')\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  processing-service:
    build:
      context: ../services/processing
    ports:
      - "5007:5007"
    restart: unless-stopped
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5007"]
    env_file:
      - ../services/processing/.env
    depends_on:
      - transcription-service
      - text-analysis-service
      - embedding-service
      - video-cut-service
      - carousel-service
      - multimodal-service
      - chromadb
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:5007/docs')\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s